--- Vehicle and firearm registry routes (spec 7.4, 7.5; 7.2 for the hot file).
---
--- Every client call into either register is defined here, and every one of
--- them obeys the same three rules.
---
--- **Access is checked on the server, on every read, including searches**
--- (invariant 4). A record the reader may not see never appears in a result --
--- not as an id, not as a plate, not as a count of what was dropped. That is
--- what `access.filterSearch` is for, and it is the acceptance criterion for
--- M2: a search that reveals a restricted record exists is a leak even when it
--- hides the contents. Nothing in this file filters rows itself.
---
--- **The session is the truth** (invariant 1). `session.agencyId` scopes every
--- query, `session.discordId` signs every write, and the VIN is generated by
--- the repo. None of the three can be named in an input, because the schema
--- layer drops any field a route did not declare.
---
--- **A restricted read is audited and a restricted query needs a reason**
--- (invariant 11, spec 7.2). The audit entry comes from the access module,
--- which writes it whether the read succeeded or was refused. The reason is
--- enforced here, before the rows are handed over: a search that would open a
--- restricted record without one is refused, nothing is disclosed, and the
--- officer re-runs it with a case number.
---
--- A refused read and a record that does not exist both answer `not_found`, on
--- purpose. Telling the two apart is precisely the information a stub is
--- careful not to give, and a deep link the reader may not open is meant to
--- show "no access" either way (4.4).

local route = FredPD.Core.route
local service = FredPD.Modules.registry
local repo = FredPD.Repo.registry

--- The record-level access module (4.5).
---
--- `FredPD.Repo.access` is the suite-wide entry point its own header describes
--- -- `read` for one row, `filterSearch` for a list -- and it is what loads
--- compartments, grants and seals and writes the audit entry. `FredPD.Modules.access`
--- is the pure half, used below only for decisions that need no database: the
--- classification on a child row that is already loaded.
local access = FredPD.Repo.access
local accessRules = FredPD.Modules.access

--- What a vehicle record is called in the generic access tables, and a firearm.
--- Both are in that module's allowlist.
local VEHICLE <const> = 'vehicle'
local FIREARM <const> = 'firearm'

--- What a flag is called when one comes back as a stub. It is a label for the
--- NUI, not a key in the access module's allowlist: a flag's compartments and
--- grants are its vehicle's, and only its classification is its own.
local FLAG <const> = 'vehicle_flag'

--- Rows affected of 0 on a versioned update means one of two things, and the
--- count alone cannot tell them apart: the record is gone, or somebody else
--- saved first. Checking existence separates them, so the officer is told to
--- reload rather than told the vehicle does not exist.
local function updateOutcome(affected, exists)
    if affected > 0 then return nil end

    return exists and FredPD.ErrorCode.CONFLICT or FredPD.ErrorCode.NOT_FOUND
end

--- Turns a repo refusal into a route error code.
local function writeOutcome(reason)
    if reason == 'not_found' then return FredPD.ErrorCode.NOT_FOUND end
    if reason == 'conflict' then return FredPD.ErrorCode.CONFLICT end

    return FredPD.ErrorCode.INTERNAL
end

--- Shapes rows that hang off a record and carry a classification of their own.
---
--- Spec 4.5: attachments inherit the record's access control and can be
--- stricter. A vehicle's flags are the case in point -- a BOLO written by the
--- intelligence unit can sit on an ordinary vehicle -- so each flag is judged on
--- its own level and comes back as a stub or not at all when the reader is not
--- cleared for it.
---
--- Rows with no classification column of their own (plate periods, firearm
--- events) are not passed through here: they inherit, and the reader has
--- already passed the parent record's check by the time this file has them.
---
--- The reader is built by the caller and passed in rather than built here.
--- Building one costs a query for the officer's Discord roles, and a handler
--- that built one per row would spend a round trip per flag on a page of
--- results -- which is how a 150 ms budget (spec 12) is lost a query at a time.
local function visibleChildren(reader, rows, recordType)
    if recordType then
        for index = 1, #rows do rows[index].recordType = recordType end
    end

    return accessRules.filterSearchResults(reader, rows)
end

--- A row that survived access filtering with its contents, rather than as a
--- stub. A stub has no id; that is the whole of its design.
local function opened(row)
    return type(row) == 'table' and row.id ~= nil
end

--- Marks rows with what kind of record they are, before access filtering.
---
--- A stub carries nothing but `restricted`, the unit to contact and this: it is
--- what lets the NUI render "Restricted record" with the right label instead of
--- an unlabelled gap in a list (4.5). It has to be on the row before filtering,
--- because the stub is built from the row and never from anything after it.
local function tagRecordType(rows, recordType)
    for index = 1, #rows do
        rows[index].recordType = recordType
    end

    return rows
end

--- The ids of the rows a reader actually opened, for a batched follow-up query.
local function openedIds(rows)
    local ids = {}

    for index = 1, #rows do
        if opened(rows[index]) then ids[#ids + 1] = rows[index].id end
    end

    return ids
end

-- -----------------------------------------------------------------------------
-- Queries (7.2)
-- -----------------------------------------------------------------------------

--- Refuses a result that would open restricted data with no reason given.
---
--- Spec 7.2: "Queries into restricted data require a reason or case number."
--- The check runs on what is about to be disclosed, after filtering and after
--- trimming to the page, because a record the reader cannot open is not a
--- disclosure and a stub is not one either.
---
--- The refusal happens before anything is returned, so the officer who has not
--- given a reason learns nothing at all -- not even that the register holds
--- something worth a reason.
---
--- @return boolean allowed
local function reasonSatisfied(rows, reason, caseNumber)
    if reason or caseNumber then return true end

    return not service.opensRestricted(rows, accessRules.isRestricted)
end

--- Logs a query (7.2). `resultCount` is what the reader was allowed to see.
local function logQuery(session, queryType, term, rows, hits, reason, caseNumber)
    repo.logQuery(session, {
        queryType = queryType,
        term = term or '',
        restricted = (reason ~= nil or caseNumber ~= nil)
            and service.opensRestricted(rows, accessRules.isRestricted),
        reason = reason,
        caseNumber = caseNumber,
        resultCount = #rows,
        hitCount = hits,
    })
end

-- =============================================================================
-- Vehicles (7.4)
-- =============================================================================

--- Attaches live flags and the hot-file hits to the rows that were opened.
---
--- One query for the whole page (spec 12), and only for rows the reader may
--- see: asking the database about the flags on a record that was filtered out
--- would be the same disclosure by a slower route.
---
--- @return number the number of rows carrying a hit
local function attachFlags(session, rows)
    local ids = openedIds(rows)
    if #ids == 0 then return 0 end

    local byVehicle = repo.liveFlagsFor(session.agencyId, ids)
    local reader = access.reader(session)
    local hits = 0

    for index = 1, #rows do
        local row = rows[index]

        if opened(row) then
            local flags = visibleChildren(reader, byVehicle[row.id] or {}, FLAG)

            row.flags = flags
            row.hits = service.vehicleHits(flags)

            if #row.hits > 0 then hits = hits + 1 end
        end
    end

    return hits
end

--- Loads one vehicle and decides whether this session may read it.
---
--- `access.read` audits the read when the record is restricted, whichever way
--- it goes (invariant 11), and returns nil when the answer is no. A vehicle
--- that does not exist returns nil too, and the route cannot tell the
--- difference -- which is the point.
local function readVehicle(session, selector)
    local row = repo.findVehicle(session.agencyId, selector)
    if not row then return nil end

    return access.read(session, VEHICLE, row)
end

--- Refuses a write that would put a record above the writer's own clearance.
---
--- The write-side half of 4.5's ladder. Both registers took `classification`
--- from input and wrote it, so an officer cleared to `internal` could mark a
--- vehicle or a firearm `secret`: a record classified out of reach of the
--- people who need it, by somebody never trusted with that level. The persons
--- module has always checked this; these two did not.
---
--- @return table|nil a refusal to return from the handler, or nil to proceed
local function refuseClassification(session, level)
    if access.canClassify(access.reader(session), level) then return nil end

    return route.refuse(FredPD.ErrorCode.FORBIDDEN, { classification = 'clearance' })
end

route.define({
    name = 'vehicle.search',
    perm = 'rms.vehicle.view',
    schema = 'VehicleSearch',
    limit = { per = 30, window = 60 },
    audit = 'vehicle.searched',
    subjectType = VEHICLE,
    auditDetail = function(_input, result)
        -- The count and whether anything hit, never the term. What an officer
        -- searched for is itself information about an investigation, and an
        -- audit log full of plates is a second register nobody meant to keep.
        return { count = result and #result.vehicles or 0, hits = result and result.hits or 0 }
    end,
    handler = function(session, input)
        local term = service.searchTerm(input.term)
        local window, limit = service.fetchWindow(input.limit)

        -- Over-fetch: access filtering removes rows after the query and never
        -- says how many, so a page asked for at exactly `limit` comes back short.
        local rows = repo.searchVehicles(session.agencyId, {
            term = term,
            ownerPersonId = input.ownerPersonId,
            ownerIdentifier = service.blankToNull(input.ownerIdentifier),
            limit = window,
        })

        local visible = service.trim(
            access.filterSearch(session, VEHICLE, tagRecordType(rows, VEHICLE)), limit
        )

        local reason = service.blankToNull(input.reason)
        local caseNumber = service.blankToNull(input.caseNumber)

        if not reasonSatisfied(visible, reason, caseNumber) then
            logQuery(session, service.queryType(term), term, {}, 0, nil, nil)
            return route.refuse(FredPD.ErrorCode.INVALID, { reason = 'required' })
        end

        local hits = attachFlags(session, visible)
        logQuery(session, service.queryType(term), term, visible, hits, reason, caseNumber)

        return { vehicles = visible, hits = hits }
    end,
})

route.define({
    name = 'vehicle.get',
    perm = 'rms.vehicle.view',
    schema = 'VehicleGet',
    audit = 'vehicle.read',
    subjectType = VEHICLE,
    handler = function(session, input)
        local plate = service.normalizePlate(input.plate)
        local vin = service.normalizeSerial(input.vin)

        if not input.id and not plate and not vin then
            return route.refuse(FredPD.ErrorCode.INVALID, { id = 'required' })
        end

        local vehicle = readVehicle(session, { id = input.id, plate = plate, vin = vin })
        if not vehicle then return route.refuse(FredPD.ErrorCode.NOT_FOUND) end

        local flags = visibleChildren(
            access.reader(session), repo.liveFlags(session.agencyId, vehicle.id), FLAG
        )
        local hits = service.vehicleHits(flags)

        -- An identifier typed by an officer is a query and is logged as one
        -- (7.2). Opening the same record from a list by its id is not: the
        -- query that found it was logged when it was run, and logging the click
        -- as well would fill the officer's history with rows they did not run.
        if plate or vin then
            logQuery(
                session, vin and 'vin' or 'plate', vin or plate,
                { vehicle }, #hits > 0 and 1 or 0,
                service.blankToNull(input.reason), service.blankToNull(input.caseNumber)
            )
        end

        return {
            id = vehicle.id,
            vehicle = vehicle,
            flags = flags,
            hits = hits,
            plates = repo.plateHistory(session.agencyId, vehicle.id),
        }
    end,
})

route.define({
    name = 'vehicle.register',
    perm = 'rms.vehicle.edit',
    schema = 'VehicleRegister',
    writes = true,
    audit = 'vehicle.registered',
    subjectType = VEHICLE,
    auditDetail = function(input)
        -- The plate, never the VIN: the audit log is read by more people than
        -- the record is, and the VIN is the record's permanent identity.
        return { plate = service.normalizePlate(input.plate) }
    end,
    handler = function(session, input)
        local plate = service.normalizePlate(input.plate)
        if not plate then return route.refuse(FredPD.ErrorCode.INVALID, { plate = 'required' }) end

        -- The VIN is not read from `input` and could not be: the schema does
        -- not declare it, so the route layer would drop it (7.4, invariant 1).
        local classRefusal = refuseClassification(session, input.classification)
        if classRefusal then return classRefusal end

        local vehicle, reason = repo.registerVehicle(session.agencyId, {
            plate = plate,
            model = service.blankToNull(input.model),
            colour = service.blankToNull(input.colour),
            colourSecondary = service.blankToNull(input.colourSecondary),
            ownerPersonId = input.ownerPersonId,
            ownerIdentifier = service.blankToNull(input.ownerIdentifier),
            registrationStatus = input.registrationStatus,
            registrationExpires = service.blankToNull(input.registrationExpires),
            insuranceStatus = input.insuranceStatus,
            insuranceExpires = service.blankToNull(input.insuranceExpires),
            classification = input.classification,
            reason = service.blankToNull(input.reason),
        }, session.discordId)

        if not vehicle then
            if reason == 'plate_taken' then
                return route.refuse(FredPD.ErrorCode.CONFLICT, { plate = 'exists' })
            end

            return route.refuse(FredPD.ErrorCode.INTERNAL)
        end

        return { id = vehicle.id, vehicle = vehicle }
    end,
})

route.define({
    name = 'vehicle.update',
    perm = 'rms.vehicle.edit',
    schema = 'VehicleUpdate',
    writes = true,
    audit = 'vehicle.updated',
    subjectType = VEHICLE,
    handler = function(session, input)
        -- Read access first, and through the access module: an officer who may
        -- edit vehicles in general may still not be cleared for this one, and
        -- an edit is a read of the record before it is a write to it.
        if not readVehicle(session, { id = input.id }) then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        local classRefusal = refuseClassification(session, input.classification)
        if classRefusal then return classRefusal end

        local affected = repo.updateVehicle(session.agencyId, input.id, input.version, {
            model = input.model,
            colour = input.colour,
            colourSecondary = input.colourSecondary,
            ownerPersonId = input.ownerPersonId,
            ownerIdentifier = input.ownerIdentifier,
            registrationStatus = input.registrationStatus,
            registrationExpires = input.registrationExpires,
            insuranceStatus = input.insuranceStatus,
            insuranceExpires = input.insuranceExpires,
            classification = input.classification,
        }, session.discordId)

        local exists = repo.findVehicle(session.agencyId, { id = input.id }) ~= nil
        local err = updateOutcome(affected, exists)
        if err then return route.refuse(err) end

        return { id = input.id }
    end,
})

route.define({
    name = 'vehicle.plate.change',
    perm = 'rms.vehicle.edit',
    schema = 'VehiclePlateChange',
    writes = true,
    audit = 'vehicle.plate.changed',
    subjectType = VEHICLE,
    auditDetail = function(input)
        return { plate = service.normalizePlate(input.plate) }
    end,
    handler = function(session, input)
        local plate = service.normalizePlate(input.plate)
        if not plate then return route.refuse(FredPD.ErrorCode.INVALID, { plate = 'required' }) end

        if not readVehicle(session, { id = input.id }) then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        local changed, reason = repo.changePlate(
            session.agencyId, input.id, input.version, plate,
            service.blankToNull(input.reason), session.discordId
        )

        if not changed then
            if reason == 'plate_taken' then
                return route.refuse(FredPD.ErrorCode.CONFLICT, { plate = 'exists' })
            end

            return route.refuse(writeOutcome(reason))
        end

        return { id = input.id, plate = plate }
    end,
})

route.define({
    name = 'vehicle.flag',
    perm = 'rms.vehicle.flag',
    schema = 'VehicleFlag',
    writes = true,
    audit = 'vehicle.flagged',
    subjectType = VEHICLE,
    auditDetail = function(input)
        return { kind = input.kind, caseNumber = input.caseNumber }
    end,
    handler = function(session, input)
        -- Reporting a vehicle stolen is a flag of kind `stolen` (7.4). There is
        -- no separate route for it: one path onto the hot file means one place
        -- the reason, the case number and the audit entry are enforced.
        local err, fields = service.validateFlag(input)
        if err then return route.refuse(err, fields) end

        if not readVehicle(session, { id = input.vehicleId }) then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        local classRefusal = refuseClassification(session, input.classification)
        if classRefusal then return classRefusal end

        local id = repo.addFlag(session.agencyId, input.vehicleId, {
            kind = input.kind,
            detail = service.blankToNull(input.detail),
            caseNumber = service.blankToNull(input.caseNumber),
            classification = input.classification,
            expiresIn = input.expiresIn,
        }, session.discordId)

        return { id = input.vehicleId, flagId = id }
    end,
})

route.define({
    name = 'vehicle.flag.clear',
    perm = 'rms.vehicle.flag',
    schema = 'VehicleFlagClear',
    writes = true,
    audit = 'vehicle.flag.cleared',
    subjectType = VEHICLE,
    handler = function(session, input)
        local flag = repo.flagById(session.agencyId, input.flagId)
        if not flag then return route.refuse(FredPD.ErrorCode.NOT_FOUND) end

        -- The vehicle's own access control governs its flags, and the flag's
        -- classification governs the flag: an officer who cannot read the
        -- record cannot clear what is on it, and neither can one who cannot
        -- read the flag they are clearing.
        if not readVehicle(session, { id = flag.vehicleId }) then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        if not opened(visibleChildren(access.reader(session), { flag }, FLAG)[1]) then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        if repo.clearFlag(session.agencyId, input.flagId, session.discordId) == 0 then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        return { id = flag.vehicleId, flagId = input.flagId }
    end,
})

-- =============================================================================
-- Firearms (7.5)
-- =============================================================================

local function readFirearm(session, selector)
    local row = repo.findFirearm(session.agencyId, selector)
    if not row then return nil end

    return access.read(session, FIREARM, row)
end

--- A firearm's hot-file state is its own status (7.5), so there is no second
--- query to batch: `hits` is computed from the row that was already filtered.
local function attachFirearmHits(rows)
    local hits = 0

    for index = 1, #rows do
        local row = rows[index]

        if opened(row) then
            row.hits = service.firearmHits(row)
            if #row.hits > 0 then hits = hits + 1 end
        end
    end

    return hits
end

route.define({
    name = 'firearm.search',
    perm = 'rms.firearm.view',
    schema = 'FirearmSearch',
    limit = { per = 30, window = 60 },
    audit = 'firearm.searched',
    subjectType = FIREARM,
    auditDetail = function(_input, result)
        return { count = result and #result.firearms or 0, hits = result and result.hits or 0 }
    end,
    handler = function(session, input)
        local term = service.searchTerm(input.term)
        local window, limit = service.fetchWindow(input.limit)

        -- A search with nothing to search on is not a query, it is the register.
        -- `searchFirearms` filters on agency alone when no filter is given, so
        -- the answer is every firearm the agency holds, ordered by serial -- and
        -- a serial is what `firearm.trace` and the ballistic index turn on. Every
        -- real use names something: a serial fragment, an owner, a status, or
        -- the officer a weapon is issued to. Listing what the quartermaster
        -- holds is `status = 'agency_issued'`, which is a filter.
        if not term
            and not input.ownerPersonId
            and not service.blankToNull(input.ownerIdentifier)
            and not input.status
            and not service.blankToNull(input.assignedOfficer)
        then
            return route.refuse(FredPD.ErrorCode.INVALID, { term = 'required' })
        end

        local rows = repo.searchFirearms(session.agencyId, {
            term = term,
            ownerPersonId = input.ownerPersonId,
            ownerIdentifier = service.blankToNull(input.ownerIdentifier),
            status = input.status,
            assignedOfficer = service.blankToNull(input.assignedOfficer),
            limit = window,
        })

        local visible = service.trim(
            access.filterSearch(session, FIREARM, tagRecordType(rows, FIREARM)), limit
        )

        local reason = service.blankToNull(input.reason)
        local caseNumber = service.blankToNull(input.caseNumber)

        if not reasonSatisfied(visible, reason, caseNumber) then
            logQuery(session, 'firearm', term, {}, 0, nil, nil)
            return route.refuse(FredPD.ErrorCode.INVALID, { reason = 'required' })
        end

        local hits = attachFirearmHits(visible)
        logQuery(session, 'firearm', term, visible, hits, reason, caseNumber)

        return { firearms = visible, hits = hits }
    end,
})

route.define({
    name = 'firearm.get',
    perm = 'rms.firearm.view',
    schema = 'FirearmGet',
    audit = 'firearm.read',
    subjectType = FIREARM,
    handler = function(session, input)
        local serial = service.normalizeSerial(input.serial)

        if not input.id and not serial then
            return route.refuse(FredPD.ErrorCode.INVALID, { id = 'required' })
        end

        local firearm = readFirearm(session, { id = input.id, serial = serial })
        if not firearm then return route.refuse(FredPD.ErrorCode.NOT_FOUND) end

        local hits = service.firearmHits(firearm)

        if serial then
            logQuery(
                session, 'firearm', serial, { firearm }, #hits > 0 and 1 or 0,
                service.blankToNull(input.reason), service.blankToNull(input.caseNumber)
            )
        end

        return {
            id = firearm.id,
            firearm = firearm,
            hits = hits,
            -- The ownership history is part of the record, not a trace report:
            -- a trace (`firearm.trace`) is the same events read for a different
            -- purpose and behind `rms.firearm.trace`.
            events = repo.firearmEvents(session.agencyId, firearm.id),
        }
    end,
})

route.define({
    name = 'firearm.register',
    perm = 'rms.firearm.edit',
    schema = 'FirearmRegister',
    writes = true,
    audit = 'firearm.registered',
    subjectType = FIREARM,
    auditDetail = function(input)
        return { serial = service.normalizeSerial(input.serial), status = input.status }
    end,
    handler = function(session, input)
        local serial = service.normalizeSerial(input.serial)
        if not serial then return route.refuse(FredPD.ErrorCode.INVALID, { serial = 'required' }) end

        if input.status ~= nil and not service.FIREARM_STATUS[input.status] then
            return route.refuse(FredPD.ErrorCode.INVALID, { status = 'not_allowed' })
        end

        if input.type ~= nil and not service.FIREARM_TYPES[input.type] then
            return route.refuse(FredPD.ErrorCode.INVALID, { type = 'not_allowed' })
        end

        local classRefusal = refuseClassification(session, input.classification)
        if classRefusal then return classRefusal end

        local firearm, reason = repo.registerFirearm(session.agencyId, {
            serial = serial,
            make = service.blankToNull(input.make),
            model = service.blankToNull(input.model),
            type = input.type,
            calibre = service.blankToNull(input.calibre),
            status = input.status,
            ownerPersonId = input.ownerPersonId,
            ownerIdentifier = service.blankToNull(input.ownerIdentifier),
            ownerParty = service.blankToNull(input.ownerParty),
            assignedOfficer = service.blankToNull(input.assignedOfficer),
            classification = input.classification,
            caseNumber = service.blankToNull(input.caseNumber),
            reason = service.blankToNull(input.reason),
        }, session.discordId)

        if not firearm then
            if reason == 'serial_taken' then
                return route.refuse(FredPD.ErrorCode.CONFLICT, { serial = 'exists' })
            end

            return route.refuse(FredPD.ErrorCode.INTERNAL)
        end

        return { id = firearm.id, firearm = firearm }
    end,
})

route.define({
    name = 'firearm.update',
    perm = 'rms.firearm.edit',
    schema = 'FirearmUpdate',
    writes = true,
    audit = 'firearm.updated',
    subjectType = FIREARM,
    handler = function(session, input)
        if not readFirearm(session, { id = input.id }) then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        -- The serial, the owner and the status are absent on purpose: each is
        -- an event in the life of the weapon and has its own route, so the
        -- ownership history can never disagree with the record (7.5).
        local classRefusal = refuseClassification(session, input.classification)
        if classRefusal then return classRefusal end

        local affected = repo.updateFirearm(session.agencyId, input.id, input.version, {
            make = input.make,
            model = input.model,
            type = input.type,
            calibre = input.calibre,
            classification = input.classification,
        }, session.discordId)

        local exists = repo.findFirearm(session.agencyId, { id = input.id }) ~= nil
        local err = updateOutcome(affected, exists)
        if err then return route.refuse(err) end

        return { id = input.id }
    end,
})

route.define({
    name = 'firearm.transfer',
    perm = 'rms.firearm.edit',
    schema = 'FirearmTransfer',
    writes = true,
    -- The most forgeable fact in the register: who a weapon belongs to. A
    -- permission snapshot that may be half an hour old is not authority enough
    -- to move one (4.2).
    sensitive = true,
    audit = 'firearm.transferred',
    subjectType = FIREARM,
    auditDetail = function(input)
        return { toPersonId = input.toPersonId, caseNumber = input.caseNumber }
    end,
    handler = function(session, input)
        local err, fields = service.validateTransfer(input)
        if err then return route.refuse(err, fields) end

        local firearm = readFirearm(session, { id = input.id })
        if not firearm then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        -- A transfer writes `status = 'registered'`, which is right for a sale
        -- and wrong for a weapon whose status is a statement about where it
        -- actually is. Without this a stolen firearm stops being stolen by
        -- being sold, and the hot file goes quiet on the serial (7.5).
        local blocked = service.transferBlockedBy(firearm.status)
        if blocked then
            return route.refuse(FredPD.ErrorCode.CONFLICT, { status = blocked })
        end

        local transferred, reason = repo.transferFirearm(session.agencyId, input.id, input.version, {
            toPersonId = input.toPersonId,
            toIdentifier = service.blankToNull(input.toIdentifier),
            toParty = service.blankToNull(input.toParty),
            fromParty = service.blankToNull(input.fromParty),
            caseNumber = service.blankToNull(input.caseNumber),
            reason = service.blankToNull(input.reason),
        }, session.discordId)

        if not transferred then return route.refuse(writeOutcome(reason)) end

        return { id = input.id }
    end,
})

route.define({
    name = 'firearm.status',
    perm = 'rms.firearm.edit',
    schema = 'FirearmStatus',
    writes = true,
    audit = 'firearm.status.set',
    subjectType = FIREARM,
    auditDetail = function(input)
        return { status = input.status, caseNumber = input.caseNumber }
    end,
    handler = function(session, input)
        -- Reporting a firearm lost or stolen (7.5) is this route: the status
        -- moves and the ownership history gains the event, in one transaction,
        -- so the register can always say when anybody was told.
        local err, fields = service.validateStatus(input)
        if err then return route.refuse(err, fields) end

        if not readFirearm(session, { id = input.id }) then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        local changed, reason = repo.setFirearmStatus(session.agencyId, input.id, input.version, {
            status = input.status,
            caseNumber = service.blankToNull(input.caseNumber),
            reason = service.blankToNull(input.reason),
        }, session.discordId)

        if not changed then return route.refuse(writeOutcome(reason)) end

        return { id = input.id, status = input.status }
    end,
})

route.define({
    name = 'firearm.assign',
    perm = 'rms.firearm.edit',
    schema = 'FirearmAssign',
    writes = true,
    audit = 'firearm.assigned',
    subjectType = FIREARM,
    auditDetail = function(input)
        return { assignedOfficer = input.assignedOfficer }
    end,
    handler = function(session, input)
        if not readFirearm(session, { id = input.id }) then
            return route.refuse(FredPD.ErrorCode.NOT_FOUND)
        end

        -- A quartermaster issues weapons to other officers, so the Discord id
        -- of the officer being issued to is an input. It identifies a grantee,
        -- not the actor: the actor is still the session, and it is the session
        -- that signs the event.
        local officer = service.blankToNull(input.assignedOfficer)

        local changed, reason = repo.assignFirearm(
            session.agencyId, input.id, input.version, officer,
            {
                caseNumber = service.blankToNull(input.caseNumber),
                reason = service.blankToNull(input.reason),
            },
            session.discordId
        )

        if not changed then return route.refuse(writeOutcome(reason)) end

        return { id = input.id, assignedOfficer = officer }
    end,
})

route.define({
    name = 'firearm.trace',
    perm = 'rms.firearm.trace',
    schema = 'FirearmTrace',
    audit = 'firearm.traced',
    subjectType = FIREARM,
    handler = function(session, input)
        local serial = service.normalizeSerial(input.serial)

        if not input.id and not serial then
            return route.refuse(FredPD.ErrorCode.INVALID, { id = 'required' })
        end

        -- A trace is a read of the record before it is a report, so it passes
        -- the same check as `firearm.get`. `rms.firearm.trace` is an extra
        -- permission on top of clearance, never a way around it.
        local firearm = readFirearm(session, { id = input.id, serial = serial })
        if not firearm then return route.refuse(FredPD.ErrorCode.NOT_FOUND) end

        local events = repo.firearmEvents(session.agencyId, firearm.id)

        return {
            id = firearm.id,
            firearm = firearm,
            events = events,
            -- The first link in the chain: where the weapon entered the
            -- register (7.5, "from a recovered firearm to first purchaser").
            origin = events[1],
        }
    end,
})
