/**
 * The shared schema package.
 *
 * One definition of every route's input shape and every shared enumeration,
 * consumed three ways: TypeScript types for the NUI and the gateway, and
 * generated Lua validator tables for the server (spec 3.5, 17.2).
 *
 * M1 adds the route and entity schemas themselves. M0 establishes the package
 * and the generation step, so nothing is ever hand-copied between Lua and TS.
 */

export { ERROR_CODES, isErrorCode } from './errors';
export type { ErrorCode } from './errors';

export {
  ACCESS_POINTS,
  ANMALAN_ROLLER,
  ANMALAN_STATUSES,
  ATAL_BESLUT,
  ATAL_DISPOSITIONS,
  BROADCAST_KINDS,
  BROTT_GRADER,
  BROTT_STAGES,
  CALL_DISPOSITIONS,
  CALL_LINK_KINDS,
  CALL_LINK_ROLES,
  CALL_LOG_KINDS,
  CALL_PRIORITIES,
  CALL_PROGRESS_STATUSES,
  CALL_STATUSES,
  CALL_TYPES,
  CLASSIFICATIONS,
  CUSTODY_ACTIONS,
  EFTERLYSNING_GRUNDER,
  EVIDENCE_DESTINATIONS,
  EVIDENCE_PACKAGING,
  EVIDENCE_SEAL_STATES,
  EVIDENCE_STATUSES,
  EVIDENCE_TYPES,
  FI_REASONS,
  FIREARM_EVENTS,
  FIREARM_STATUSES,
  FIREARM_TYPES,
  FRIHET_STATUSES,
  FU_LEDARE_KINDS,
  FU_STATUSES,
  HAK_METHODS,
  HAK_STATUSES,
  HAK_TARGETS,
  HOTLIST_REASONS,
  IMPOUND_HELD_REASONS,
  INTEL_CASE_STATUSES,
  INTEL_CONFIDENCE,
  INTEL_ORG_STATUSES,
  INTEL_ORG_TYPES,
  INTEL_PERSON_STATUSES,
  INTEL_SOURCES,
  LAB_ANALYSES,
  LAB_ANALYSIS_STATUSES,
  LAB_PRIORITIES,
  LAB_REQUEST_STATUSES,
  LAB_RESULT_CODES,
  LOCATION_HAZARD_KINDS,
  LOCATION_KEYHOLDER_ROLES,
  LOCATION_KINDS,
  ORDNINGSBOT_STATUSES,
  PERSON_CAUTION_KINDS,
  PERSON_SEXES,
  PERSONNEL_ISSUE_KINDS,
  PLACEMENT_ACCESS_POINTS,
  PLACEMENT_INTERACTIONS,
  PLACEMENT_KINDS,
  SCENE_STATUSES,
  SELF_SET_UNIT_STATUSES,
  SPANING_TARGETS,
  STOP_KINDS,
  STOP_REASONS,
  STOP_RESULTS,
  STOP_SEARCHES,
  SUPERVISOR_UNIT_STATUSES,
  TVANG_DECIDERS,
  TVANG_KINDS,
  TVANG_TARGETS,
  UNIT_STATUSES,
  VEHICLE_FLAG_KINDS,
  VEHICLE_INSURANCE_STATUSES,
  VEHICLE_REGISTRATION_STATUSES,
} from './enums';
export type {
  AccessPoint,
  AnmalanRoll,
  AnmalanStatus,
  AtalBeslut,
  AtalDisposition,
  BroadcastKind,
  BrottGrad,
  BrottStage,
  CallDisposition,
  CallLinkKind,
  CallLinkRole,
  CallLogKind,
  CallPriority,
  CallProgressStatus,
  CallStatus,
  CallType,
  Classification,
  CustodyAction,
  EfterlysningGrund,
  EvidenceDestination,
  EvidencePackaging,
  EvidenceSealState,
  EvidenceStatus,
  EvidenceType,
  FiReason,
  FirearmEvent,
  FirearmStatus,
  FirearmType,
  FrihetStatus,
  FuLedareKind,
  FuStatus,
  HakMethod,
  HakStatus,
  HakTarget,
  HotlistReason,
  ImpoundHeldReason,
  LocationHazardKind,
  LocationKeyholderRole,
  LocationKind,
  IntelCaseStatus,
  IntelConfidence,
  IntelOrgStatus,
  IntelOrgType,
  IntelPersonStatus,
  IntelSource,
  LabAnalysisKind,
  LabAnalysisStatus,
  LabPriority,
  LabRequestStatus,
  LabResultCode,
  OrdningsbotStatus,
  PersonCautionKind,
  PersonSex,
  PersonnelIssueKind,
  PlacementInteraction,
  PlacementKind,
  SceneStatus,
  SpaningTarget,
  StopKind,
  StopReason,
  StopResult,
  StopSearch,
  TvangDecider,
  TvangKind,
  TvangTarget,
  UnitStatus,
  VehicleFlagKind,
  VehicleInsuranceStatus,
  VehicleRegistrationStatus,
} from './enums';

export { schemas } from './schemas';
export type { FieldSpec, Schema, SchemaName } from './schemas';
